[theme]
base = "dark"
primaryColor = "#0C4AD1"
backgroundColor = "#0A0E1A"
secondaryBackgroundColor = "#131832"
textColor = "#FFFFFF"
font = "sans serif"
baseFontSize = 16

[server]
headless = true

[browser]
gatherUsageStats = false
